version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      DB_URL: db
    depends_on:
      - db
  
  db:
    image: mongo
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:

volumes:
  mongo-data: