require('dotenv').config()

var CONFIG = {}
CONFIG.RAZOR_PAY_PRIVATE_KEY = process.env.RAZOR_PAY_PRIVATE_KEY
CONFIG.RAZOR_PAY_KEY_ID = process.env.RAZOR_PAY_KEY_ID
CONFIG.LIVE_DB = process.env.LIVE_DB
CONFIG.port = process.env.PORT || 3000
CONFIG.APP_ENV = process.env.NODE_ENV || 'development'

CONFIG.DB_URL = process.env.DB_URL || '127.0.0.1'
CONFIG.DB_NAME = process.env.DB_NAME || 'template'
CONFIG.DB_USERNAME = process.env.DB_USERNAME
CONFIG.DB_PASSWORD = process.env.DB_PASSWORD

CONFIG.SMS_API_URL =
  process.env.SMS_API_URL ||
  'http://k3digitalmedia.co.in/websms/api/http/sendsms.php'
CONFIG.SMS_API_USERNAME = process.env.SMS_API_USERNAME || 'wiseotherwise'
CONFIG.SMS_API_KEY = process.env.SMS_API_KEY || 'E8836-83C6B'
CONFIG.SMS_API_SENDER = process.env.SMS_API_SENDER || 'DSGNRR'

CONFIG.SENDGRID_EMAIL_API_KEY =
  process.env.SENDGRID_EMAIL_API_KEY ||
  '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'

CONFIG.AWS_ACCESS_KEY_ID =
  process.env.AWS_ACCESS_KEY_ID || 'AKIA3N7NMAQWEVJLPVIC'
CONFIG.AWS_SECRET_ACCESS_KEY =
  process.env.AWS_SECRET_ACCESS_KEY ||
  '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'
CONFIG.AWS_S3_BUCKET = process.env.AWS_S3_BUCKET || 'designerrs'
CONFIG.AWS_S3_BUCKET_ENDPOINT =
  process.env.AWS_S3_BUCKET_ENDPOINT ||
  'https://designerrs.s3.ap-south-1.amazonaws.com'
CONFIG.AWS_S3_BUCKET_REGION = process.env.AWS_S3_BUCKET_REGION || 'ap-south-1'

CONFIG.AWS_COGNITO_REGION = 'ap-south-1'
CONFIG.AWS_COGNITO_USER_POOL_ID = 'ap-south-1_EqYeey1dl'
CONFIG.AWS_COGNITO_CLIENT_ID = '3vv2ve70kjlougdkl7prshdpkv'

CONFIG.FIREBASE_ACCOUNT_TYPE =
  process.env.FIREBASE_ACCOUNT_TYPE || 'service_account'
CONFIG.FIREBASE_PROJECT_ID = process.env.FIREBASE_PROJECT_ID
CONFIG.FIREBASE_PRIVATE_KEY_ID = process.env.FIREBASE_PRIVATE_KEY_ID
CONFIG.FIREBASE_PRIVATE_KEY = process.env.FIREBASE_PRIVATE_KEY.replace(
  /\\n/g,
  '\n',
)
CONFIG.FIREBASE_CLIENT_EMAIL = process.env.FIREBASE_CLIENT_EMAIL
CONFIG.FIREBASE_CLIENT_ID = process.env.FIREBASE_CLIENT_ID
CONFIG.FIREBASE_AUTH_URI = process.env.FIREBASE_AUTH_URI
CONFIG.FIREBASE_TOKEN_URI = process.env.FIREBASE_TOKEN_URI
CONFIG.FIREBASE_AUTH_PROVIDER_X509_CERT_URL =
  process.env.FIREBASE_AUTH_PROVIDER_X509_CERT_URL
CONFIG.FIREBASE_CLIENT_X509_CERT_URL = process.env.FIREBASE_CLIENT_X509_CERT_URL
CONFIG.FIREBASE_RT_DB_URL = process.env.FIREBASE_RT_DB_URL

module.exports = CONFIG
